AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - '**/config.ru'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'elm-stuff/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 100
  Enabled: true

Style/DotPosition:
  EnforcedStyle: trailing
  Enabled: true

Style/SymbolArray:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

EmptyMethod:
  EnforcedStyle: 'expanded'
  Enabled: true

StringLiterals:
  EnforcedStyle: 'single_quotes'
  Enabled: true
